// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNd-6Ho-aafkOJOWQpnrar93aAQaw_KGw',
    appId: '1:877344514678:web:77e5c07ccbbacbca183557',
    messagingSenderId: '877344514678',
    projectId: 'boostme-147c6',
    authDomain: 'boostme-147c6.firebaseapp.com',
    storageBucket: 'boostme-147c6.appspot.com',
    measurementId: 'G-65TDJJTBKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6359A-WonE5F-F4JTGspfsJK7WAAH5So',
    appId: '1:877344514678:android:07884b8fd66f9f20183557',
    messagingSenderId: '877344514678',
    projectId: 'boostme-147c6',
    storageBucket: 'boostme-147c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s1b36GFgHq72I2gVpLX9WZojU0H6Ekg',
    appId: '1:877344514678:ios:ace0f1d19423a155183557',
    messagingSenderId: '877344514678',
    projectId: 'boostme-147c6',
    storageBucket: 'boostme-147c6.appspot.com',
    iosBundleId: 'com.example.boostme2',
  );

}